version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    networks:
       - proxy
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:

networks:
  proxy:
    external: true